language: java

jdk:
  - openjdk8
  - oraclejdk8

install: mvn -f src install -DskipTests=true
script: mvn -f src test
  
branches:
 only:
 - master

notifications:
  email: false
  
cache:
directories:
- $HOME/.m2 

